# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Hyunwoo Kwon
description: >- # this means to ignore newlines until "baseurl:"
  Researcher in Analysis&PDEs.
baseurl: "/" # the subpath of the site
url: "https://willkwon-math.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile.png
#google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Talks
    - name: Teaching
    - name: Notes

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: willkwon@sogang.ac.kr
      link: mailto:willkwon@sogang.ac.kr 
  follow: 
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
